//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midterm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [Bind(Exclude = "Id")]
    public partial class CourseData
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        [DisplayName("Course Code")]
        [StringLength(10, ErrorMessage = "The Course Code Cannot Be"), Required(ErrorMessage = "A Course Code is required")]
        public string CourseCode { get; set; }
        [DisplayName("Course Name")]
        [Required(ErrorMessage = "A Course Name is required")]
        public string CourseName { get; set; }
        [DisplayName("Course Description")]
        [DataType(DataType.MultilineText)] 
        [Required(ErrorMessage = "A Course Description is required")]
        public string CourseDescription { get; set; }
        [DisplayName("Course Cost")]
        [Range(0, 9999999999999999.99, ErrorMessage = "The Cost must be between $0 and $9999999999999999.99 "), Required(ErrorMessage = "A Course Cost is required")]
        public decimal CourseCost { get; set; }
    }
}
